# Generated by Django 6.0 on 2026-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='lrclib', max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('original_hash', models.CharField(max_length=64)),
                ('translated_text', models.TextField(blank=True)),
                ('aligned_lines', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id', 'language', 'original_hash'), name='unique_song_translation')],
            },
        ),
    ]
